wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1650839022
    t:
      1:
      - 1
      - 9
      - 10
      - 41
      - 50
      - 55
      3:
      - 13
      - 23
      4: 3.7.4
      5: 0.12.15
      8:
      - 5
