wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: gradients/model\.fc\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.fc\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.fc\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.fc\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.fc\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.fc\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.2\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.1\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.convShortcut\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.convShortcut\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.convShortcut\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block3\.layer\.0\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.2\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.1\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.convShortcut\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.convShortcut\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.convShortcut\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block2\.layer\.0\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.2\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.1\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.convShortcut\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.convShortcut\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.convShortcut\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.block1\.layer\.0\.bn1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/model\.conv1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/model\.conv1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/model\.conv1\.weight.bins
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: top1_acc
      5: 1
      6:
      - 1
    - 1: top5_acc
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy
      5: 1
      6:
      - 1
    - 1: val_top_5_accuracy
      5: 1
      6:
      - 1
    python_version: 3.7.4
    start_time: 1651064166
    t:
      1:
      - 1
      - 9
      - 10
      - 41
      - 50
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.7.4
      5: 0.12.15
      8:
      - 5
adaptive:
  desc: null
  value: true
density:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.095409631107804
percent_valid_examples:
  desc: null
  value: 0.1
rho:
  desc: null
  value: 1.5392140101476401
wandb:
  desc: null
  value: true
weigth_decay:
  desc: null
  value: 0.0005
