defaults:
  - _self_
  - masking: Static
  - dataset: CIFAR10
  - optimizer: SGD
  - hydra
  - override hydra/launcher: joblib
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

exp_name: ${masking.name}
seed: 0
multi_seed: []
model: wrn-22-2

# Train args
device: cuda # cpu or cuda

# Logging, Saving, Resuming
log_interval: 100
ckpt_dir: ckpts
ckpt_interval: ${optimizer.epochs} # Dont save any intermediate weights, just final
val_interval: 1
resume: False

# W&B
wandb:
  use: False
  api_key: ${hydra:runtime.cwd}/wandb_api.key
  entity: luis_alfredo
  project: sparse_training
  name: ${exp_name}

wandb_api_key: ${hydra:runtime.cwd}/wandb_api.key
