defaults:
  - _self_
  - dataset: CIFAR10
  - hydra
  - override hydra/launcher: joblib
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
# Train args
device: cuda # cpu or cuda

masking:
  name: RigL
  sparse_init: erdos-renyi-kernel
  density: 0.1  # The density of the overall sparse network.
  prune_rate: 0.3  # The pruning rate / prune rate.
  decay_schedule: cosine  # The decay schedule for the pruning rate. Default: cosine. Choose from: cosine, linear
  apply_when: step_end  # or step_end
  interval: 1 # Which epochs or steps to apply at
  end_when: -1
exp_name: population_experiment
# Logging, Saving, Resuming
log_interval: 100
log_interval_population: 1
ckpt_dir: ckpts
ckpt_interval: ${optimizer.epochs} # Dont save any intermediate weights, just final
val_interval: 1
resume: True

 #override individual_settings/cifar10_wrn_22_2_rigl_modified
target_value: 0.9
  # Optimizer
optimizer:
  epochs: 10
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  decay_frequency: 30000
  decay_factor: 0.2
# Population algorithm parameters
population_size: 10
generations: 2
