wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: ignite
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.4
    start_time: 1650759632
    t:
      1:
      - 1
      - 9
      - 10
      - 41
      - 50
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.7.4
      5: 0.12.15
      8:
      - 5
adaptive:
  desc: null
  value: true
density:
  desc: null
  value: 0.05
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.09540963110780444
percent_valid_examples:
  desc: null
  value: 0.1
rho:
  desc: null
  value: 1.5392140101476401
wandb:
  desc: null
  value: true
